Repository hatchet/hatchet, pull requests merged in 2020-10, with the labels that each got.

#250 Query Language Doc Update: User Guide
  docs/query_language_guide.rst
  docs/user_guide.rst
Labels: docs, ready-for-review

#263 Fix roundtrip table columns to be more flexible
  hatchet/external/roundtrip/roundtripTree.js
Labels: ready-for-review

#268 literal reader: node type can be a Frame attribute
  hatchet/graphframe.py
  hatchet/tests/conftest.py
Labels: readers, ready-for-review

#274 Add pyinstrument reader, test, and data.
  hatchet/graphframe.py
  hatchet/readers/pyinstrument_reader.py
  hatchet/tests/conftest.py
  hatchet/tests/data/pyinstrument-hatchet-json/pyinstrument-hatchet-profile.json
  hatchet/tests/pyinstrument.py
Labels: readers

#278 update literal graphs in examples
  docs/examples/read/dag_literal.py
  docs/examples/tutorial/hatchet_query_examples.ipynb
  docs/examples/tutorial/roundtrip-demo.ipynb
Labels: ready-for-review
