Repository hatchet/hatchet, pull requests merged in 2020-11, with the labels that each got.

#270 Add support for non-DataFrame data to high-level query language
  hatchet/query_matcher.py
  hatchet/tests/query.py
Labels: enhancement, ready-for-review

#284 docs: add new page for publications, posters, and tutorials
  docs/index.rst
  docs/publications.rst
Labels: docs

#279 literal reader: can define nodes to be duplicated
  hatchet/graphframe.py
  hatchet/readers/literal_reader.py
  hatchet/tests/caliper.py
  hatchet/tests/conftest.py
  hatchet/tests/graph_literal.py
  hatchet/tests/graphframe.py
  hatchet/tests/hpctoolkit.py
  hatchet/tests/pyinstrument.py
Labels: readers, ready-for-review

#286 docs: add section on interactive jupyter visualization framework
  docs/getting_started.rst
  docs/images/jupyter-query-filter.png
  docs/images/jupyter-tree-overview.png
  docs/user_guide.rst
Labels: docs, ready-for-review

#287 fix python2 ascii error for terminal tree output
  hatchet/external/console.py
  hatchet/graphframe.py
Labels: bug, ready-for-review

#282 Fixing Bugs with Squash.
  hatchet/graphframe.py
Labels: ready-for-review

#292 Docs: finish basic tutorial
  docs/basic_tutorial.rst
  docs/images/basic-tutorial/01-dataframe.png
  docs/images/basic-tutorial/02-tree.png
  docs/images/basic-tutorial/03-dataframe-sorted.png
  docs/images/basic-tutorial/04-dataframe-with-new-column.png
  docs/images/basic-tutorial/05-tree-inc-time.png
  docs/images/basic-tutorial/06-tree-depth.png
  docs/images/basic-tutorial/07-tree-invert-colormap.png
  docs/images/basic-tutorial/08-dataframe-index-levels.png
  docs/images/basic-tutorial/09-dataframe-drop-index-levels.png
  docs/images/basic-tutorial/10-graphframe-filter.png
  docs/images/basic-tutorial/11-graphframe-squash.png
  docs/images/basic-tutorial/12-lulesh-64cores.png
  docs/images/basic-tutorial/13-divide-graphframes.png
  docs/images/basic-tutorial/drop-index-levels-dataframe.png
  docs/images/basic-tutorial/drop-index-levels.png
  docs/images/basic-tutorial/filter-graphframe.png
  docs/images/basic-tutorial/query-index-levels.png
  docs/images/basic-tutorial/squash-graphframe.png
  docs/index.rst
Labels: docs, ready-for-review

#283 add type to frame if not specified with Node initialization
  docs/examples/read/dag_literal.py
  docs/examples/tutorial/hatchet_query_examples.ipynb
  docs/examples/tutorial/roundtrip-demo.ipynb
  hatchet/external/roundtrip/roundtripTree.js
  hatchet/frame.py
  hatchet/graphframe.py
  hatchet/readers/literal_reader.py
  hatchet/tests/conftest.py
  hatchet/tests/frame.py
  hatchet/tests/graphframe.py
  hatchet/tests/node.py
Labels: ready-for-review

#294 remove tree parameters: unicode, color, and threshold
  hatchet/external/console.py
  hatchet/graphframe.py
  hatchet/tests/graphframe.py
  hatchet/util/deprecated.py
Labels: ready-for-review

#289 update CHANGELOG for v1.3.0 release
  CHANGELOG.md
  README.md
  hatchet/version.py
  pyproject.toml
Labels: ready-for-review

#251 Initial implementation of timemory support
  .travis.yml
  docs/examples/read/timemory.py
  hatchet/graphframe.py
  hatchet/readers/timemory_reader.py
  hatchet/tests/conftest.py
  hatchet/tests/data/timemory/wall.tree.json
  hatchet/tests/timemory_func.py
  hatchet/tests/timemory_test.py
Labels: readers, ready-for-review
