Repository hatchet/hatchet, pull requests merged in 2021-04, with the labels that each got.

#343 minor fix to setting PYTHONPATH in install script
  install.sh
Labels: WIP

#369 Temporary CI fix for #368
  .travis.yml
Labels: bug, coverage, ready-for-review

#373 Urgent Bugfix: Fixes a syntax error in .travis.yml that prevented Travis from running
  .travis.yml
  hatchet/readers/cprofile_reader.py
  hatchet/tests/profiler.py
Labels: bug, ready-for-review, travis
