Repository hatchet/hatchet, pull requests merged in 2021-02, with the labels that each got.

#314 Adds range feature to High-Level Query Language
  hatchet/query_matcher.py
  hatchet/tests/query.py
Labels: bug, enhancement, ready-for-review

#323 Fix error where the same function in different files would clobber nodes in cprofiles
  hatchet/readers/cprofile_reader.py
Labels: ready-for-review

#305 calculate min, max without modifying the dataframe.
  hatchet/external/console.py
Labels: ready-for-review

#304 caliper-reader: handle multiple hierarchies in caliper json
  hatchet/readers/caliper_reader.py
Labels: ready-for-review

#331 docs: update interactive visualization description
  docs/user_guide.rst
Labels: docs, ready-for-review

#327 add gf.show_metric_columns() to query dataframe columns
  hatchet/external/console.py
  hatchet/graphframe.py
  hatchet/tests/graphframe.py
Labels: ready-for-review
