Repository hatchet/hatchet, pull requests merged in 2021-08, with the labels that each got.

#252 add python-based caliper reader
  docs/examples/read/caliper_cali_query.py
  docs/examples/read/caliper_caliperreader.py
  docs/examples/read/caliper_caliperreader_cali.py
  hatchet/graphframe.py
  hatchet/readers/caliper_native_reader.py
  hatchet/tests/caliper.py
  hatchet/tests/data/caliper-example-cali/example-profile.cali
  requirements.txt
  setup.py
Labels: readers, ready-for-review

#387 Add new colormaps.
  hatchet/external/console.py
  hatchet/graphframe.py
  hatchet/tests/caliper.py
  hatchet/tests/cprofile.py
  hatchet/tests/graphframe.py
  hatchet/tests/hpctoolkit.py
  hatchet/tests/pyinstrument.py
  hatchet/tests/tau.py
  hatchet/tests/timemory_test.py
  hatchet/util/colormaps.py
Labels: ready-for-review

#388 roundtrip: pan and zoom
  docs/examples/tutorial/roundtrip-demo.ipynb
  hatchet/external/roundtrip/roundtripTree.js
Labels: ready-for-review, vis

#389 Roundtrip: refactor, add pan and zoom, modify default layout
  hatchet/external/roundtrip/roundtrip.py
  hatchet/external/roundtrip/roundtripTree.js
Labels: ready-for-review, vis
