Repository hatchet/hatchet, pull requests merged in 2021-07, with the labels that each got.

#390 Add multiprocess package to setup.py
  setup.py
Labels: ready-for-review

#392 Refactor CypherQuery so that it's more consistent with other Query classes
  hatchet/query.py
  hatchet/tests/query.py
Labels: enhancement, query-language

#339 add TAU reader
  hatchet/graphframe.py
  hatchet/readers/tau_reader.py
  hatchet/tests/conftest.py
  hatchet/tests/data/tau-cpi-mpi/profile.0.0.0
  hatchet/tests/data/tau-cpi-mpi/profile.1.0.0
  hatchet/tests/data/tau-cpi-mpi/profile.2.0.0
  hatchet/tests/data/tau-cpi-mpi/profile.3.0.0
  hatchet/tests/tau.py
Labels: readers, ready-for-review

#385 Roundtrip refactor into MVC
  hatchet/external/roundtrip/roundtrip.py
  hatchet/external/roundtrip/roundtripTree.js
Labels: ready-for-review, vis

#403 bugfix: tau-reader: use consistent ordering of files
  hatchet/readers/tau_reader.py
Labels: bug, ready-for-review
