Repository hatchet/hatchet, pull requests merged in 2022-06, with the labels that each got.

#398 add high-level API
  hatchet/__init__.py
  hatchet/chopper.py
  hatchet/graphframe.py
  hatchet/tests/chopper.py
Labels: status: ready for review

#418 add Score-P reader for cubex files
  hatchet/graphframe.py
  hatchet/readers/scorep_reader.py
  hatchet/tests/conftest.py
  hatchet/tests/data/scorep-cpi-cubex/profile.cubex
  hatchet/tests/scorep.py
  requirements.txt
  setup.py
Labels: status: ready to merge

#429 add Python 3.9 and 3.10 to the list of builds
  .github/workflows/unit-tests.yaml
Labels: status: WIP, area: CI

#454 Adding APEX JSON reader.
  hatchet/graphframe.py
  hatchet/readers/apex_reader.py
Labels: status: ready for review, area: readers
