Repository hatchet/hatchet, pull requests merged in 2024-02, with the labels that each got.

#518 fix: formatting issues with newer python and black versions
  hatchet/readers/caliper_reader.py
  hatchet/readers/timemory_reader.py
  hatchet/writers/dataframe_writer.py
  pyproject.toml
Labels: type: bug, status: ready for review, priority: high, area: build

#510 hpctoolkit_v4_reader: optimize performance
  hatchet/readers/hpctoolkit_v4_reader.py
Labels: type: bug, status: ready for review, priority: high

#485 docs: Add Chopper API docs
  docs/chopper_api.rst
  docs/images/chopper/CG-toy.png
  docs/images/chopper/eff3.png
  docs/images/chopper/hot-path-toy2.png
  docs/images/chopper/load_imb_toy.png
  docs/images/chopper/pivot-table.png
  docs/images/chopper/simple_cct_vis.png
  docs/images/chopper/unify_multiple_graphframes.png
  docs/user_guide.rst
Labels: status: ready for review, priority: normal, area: chopper, type: documentation

#470 graphframe: unify multiple graphframes
  hatchet/graphframe.py
  hatchet/node.py
  hatchet/tests/graphframe.py
Labels: type: feature, status: ready for review, priority: high, area: graphframe

#499 feature: add speedup_efficiency
  hatchet/chopper.py
  hatchet/tests/chopper.py
Labels: type: feature, status: ready for review, priority: high, area: chopper

#517 chopper: correlation analysis
  hatchet/chopper.py
  hatchet/graphframe.py
  hatchet/tests/chopper.py
Labels: type: feature, status: ready for review, priority: high, area: chopper

#525 chopper: call unify_multiple_graphframes in speedup_efficiency
  hatchet/chopper.py
Labels: type: bug, status: ready for review, priority: high, area: chopper

#497 chopper: add load imbalance statistics
  hatchet/chopper.py
  hatchet/graphframe.py
Labels: type: feature, status: WIP, priority: high, area: chopper

#526 CI: Run wheel builders only when label = type:release
  .github/workflows/wheels.yml
Labels: type: release, status: ready for review, area: build

#531 setup: Install cython as a build dependency
  setup.py
Labels: type: release

#532 release candidate v1.4.0rc3
  docs/conf.py
  hatchet/version.py
  pyproject.toml
Labels: type: release

#533 setup: add setuptools as a build dependency
  setup.py
Labels: type: release

#534 release candidate v1.4.0rc4
  docs/conf.py
  hatchet/version.py
  pyproject.toml
Labels: type: release

#535 setup: use pyproject.toml to declare dependencies
  .github/workflows/wheels.yml
  pyproject.toml
  setup.py
Labels: type: release

#537 release candidate v1.4.0rc5
  docs/conf.py
  hatchet/version.py
  pyproject.toml
Labels: type: release
